jobs:
    include:
        - os: linux
          dist: bionic
          gobuild_args: -tags hyperscan_v4

        - os: linux
          dist: focal

        - os: osx
          osx_image: xcode12.2

addons:
    apt:
        packages:
            - libhyperscan-dev
            - libpcap-dev
            - tree
    homebrew:
        packages:
            - pkg-config
            - hyperscan
            - libpcap
            - tree

env:
    global:
        - GO111MODULE=on
        - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

language: go

go:
    - 1.14.x
    - 1.15.x
    - master

after_failure:
    - echo `pwd`
    - tree -h
