dist: bionic

os:
    - linux
    - osx

osx_image: xcode12.2

addons:
    apt:
        packages:
            - libhyperscan-dev
            - libpcap-dev
            - tree
    homebrew:
        packages:
            - pkg-config
            - hyperscan
            - libpcap
            - tree

env:
    global:
        - GO111MODULE=on
        - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
install:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install hyperscan libpcap tree; fi

language: go

go:
    - 1.13.x
    - 1.14.x
    - 1.15.x
    - master

gobuild_args: -tags hyperscan_v4

after_failure:
    - echo `pwd`
    - tree -h
